services:
  -gateway:
    image: ${_IMAGE:-:local}
    environment:
      HOME: /home/node
      TERM: xterm-256color
      _GATEWAY_TOKEN: ${_GATEWAY_TOKEN}
      CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
    volumes:
      - ${_CONFIG_DIR}:/home/node/.
      - ${_WORKSPACE_DIR}:/home/node/./workspace
    ports:
      - "${_GATEWAY_PORT:-18789}:18789"
      - "${_BRIDGE_PORT:-18790}:18790"
    init: true
    restart: unless-stopped
    command:
      [
        "node",
        "dist/index.js",
        "gateway",
        "--bind",
        "${_GATEWAY_BIND:-lan}",
        "--port",
        "18789",
      ]

  -cli:
    image: ${_IMAGE:-:local}
    environment:
      HOME: /home/node
      TERM: xterm-256color
      _GATEWAY_TOKEN: ${_GATEWAY_TOKEN}
      BROWSER: echo
      CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
    volumes:
      - ${_CONFIG_DIR}:/home/node/.
      - ${_WORKSPACE_DIR}:/home/node/./workspace
    stdin_open: true
    tty: true
    init: true
    entrypoint: ["node", "dist/index.js"]


